// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrf_aln8rySsVVlhaaUdJueTyZYof-SPU',
    appId: '1:353192778567:web:f8bd9285ee47cc3f8f8a62',
    messagingSenderId: '353192778567',
    projectId: 'flutternew-96801',
    authDomain: 'flutternew-96801.firebaseapp.com',
    storageBucket: 'flutternew-96801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4AARcovFkK-ocTmfLVEVsNXXGBQbsqqM',
    appId: '1:353192778567:android:d01780a5031385768f8a62',
    messagingSenderId: '353192778567',
    projectId: 'flutternew-96801',
    storageBucket: 'flutternew-96801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABdR8B9z4urQZvF0-6_zh7VHR4hshLRqA',
    appId: '1:353192778567:ios:22d197b92bfd0a848f8a62',
    messagingSenderId: '353192778567',
    projectId: 'flutternew-96801',
    storageBucket: 'flutternew-96801.appspot.com',
    iosClientId: '353192778567-ccu99eusfs7nodhs30l77sm61nmseost.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotificationusingfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABdR8B9z4urQZvF0-6_zh7VHR4hshLRqA',
    appId: '1:353192778567:ios:ec206d58ef673f578f8a62',
    messagingSenderId: '353192778567',
    projectId: 'flutternew-96801',
    storageBucket: 'flutternew-96801.appspot.com',
    iosClientId: '353192778567-p9ivvhh3a7aekknlg7m35g2s71dvlusl.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushnotificationusingfirebase.RunnerTests',
  );
}
